version: '3.8'

services:
  ml-backend:
    build: .
    container_name: draw-app-ml-backend
    ports:
      - "3003:3003"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=3003
      - DEBUG=false
      - LOG_LEVEL=INFO
      - ENABLE_GPU=false
      - MODEL_CACHE_DIR=./models
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - draw-app-network

  # Optional: Redis for caching
  redis:
    image: redis:7-alpine
    container_name: draw-app-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - draw-app-network

  # Optional: PostgreSQL for storing analysis results
  postgres:
    image: postgres:15-alpine
    container_name: draw-app-postgres
    environment:
      - POSTGRES_DB=draw_app_ml
      - POSTGRES_USER=ml_user
      - POSTGRES_PASSWORD=ml_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - draw-app-network

volumes:
  redis_data:
  postgres_data:

networks:
  draw-app-network:
    driver: bridge
